url: https://gustafbroman.github.io/blog
baseurl: /

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: post
      author: "Gustaf Broman"