url: "https://broman.blog"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      name: "Broman's Blog"
      title: "Broman's Blog"
      layout: post
      author: "Alexander Broman"
      category: "micro-essays"
