url: https://broman.blog/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      name: "Broman's Blog"
      layout: post
      author: "Gustaf Broman"

social:
  name: Gustaf Broman
  links:
    - https://www.twitter.com/gustafbroman
    - https://www.goodreads.com/gustafbroman
    - https://www.github.com/gustafbroman
    - https://www.quora.com/gustaf-broman
    - https://www.youtube.com/channel/UCZn_YFOirdcayfrGzT4P1RA