url: "https://broman.blog"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      name: "broman.blog"
      title: "broman.blog"
      image: "/assets/images/profile.jpg"
      layout: post
      author: "bromanbuilds"
      category: "micro-essays"
